-- ALTER TABLE Company
-- MODIFY Id INT AUTO_INCREMENT,
-- ADD PRIMARY KEY (Id),
-- MODIFY Name VARCHAR(31);

-- ALTER TABLE Team
-- ADD PRIMARY KEY (Id),
-- MODIFY Id INT AUTO_INCREMENT,
-- MODIFY Caption VARCHAR(31),
-- MODIFY CompanyId INT NOT NULL,
-- ADD CONSTRAINT FOREIGN KEY (CompanyId) REFERENCES Company (Id);

-- ALTER TABLE User
-- ADD PRIMARY KEY (Id),
-- MODIFY Id INT AUTO_INCREMENT,
-- MODIFY FirstName VARCHAR(63),
-- MODIFY LastName VARCHAR(63),
-- MODIFY Login VARCHAR(63),
-- MODIFY Password VARCHAR(63),
-- DROP COLUMN IsSystemAdministrator,
-- MODIFY EMail VARCHAR(127),
-- MODIFY Phone VARCHAR(63),
-- MODIFY Clearance TINYINT UNSIGNED,
-- MODIFY Beneficiary VARCHAR(63),
-- MODIFY BIC VARCHAR(63),
-- MODIFY Iban VARCHAR(63),
-- MODIFY Street VARCHAR(63),
-- MODIFY City VARCHAR(63),
-- MODIFY Canton VARCHAR(16),
-- MODIFY Zip MEDIUMINT UNSIGNED,
-- MODIFY TeamId INT NOT NULL,
-- ADD CONSTRAINT FOREIGN KEY (TeamId) REFERENCES Team (Id),
-- MODIFY CompanyId INT NOT NULL,
-- ADD CONSTRAINT FOREIGN KEY (CompanyId) REFERENCES Company (Id),
-- MODIFY IsLocked BOOLEAN;

-- UPDATE Account SET M2Available = NULL WHERE M2Available = '';
-- UPDATE Account SET M2Constructed = NULL WHERE M2Constructed = '';
-- UPDATE Account SET RawSurface = NULL WHERE RawSurface = '';
-- UPDATE Account SET Rooms = NULL WHERE Rooms = '';
-- UPDATE Account SET Surface = NULL WHERE Surface = '';
-- UPDATE Account SET ReceivedDate = NULL WHERE ReceivedDate = '';
-- UPDATE Account SET ExpertizedDate = NULL WHERE ExpertizedDate = '';
-- UPDATE Account SET NotarizedDate = NULL WHERE NotarizedDate = '';
-- UPDATE Account SET PaidDate = NULL WHERE PaidDate = '';
-- UPDATE Account SET DecidedDate = NULL WHERE DecidedDate = '';
-- UPDATE Account SET TransmitedDate = NULL WHERE TransmitedDate = '';

-- ALTER TABLE Account
-- MODIFY Id INT AUTO_INCREMENT,
-- ADD PRIMARY KEY (Id),
-- MODIFY CreationDate DATETIME,
-- MODIFY UpdateDate DATETIME,
-- MODIFY State SMALLINT UNSIGNED,
-- MODIFY M2Available SMALLINT UNSIGNED,
-- MODIFY M2Constructed SMALLINT UNSIGNED,
-- MODIFY M3s SMALLINT UNSIGNED,
-- MODIFY RawSurface SMALLINT UNSIGNED,
-- MODIFY Rooms TINYINT UNSIGNED,
-- MODIFY Surface SMALLINT UNSIGNED,
-- MODIFY HabitatType TINYINT UNSIGNED,
-- DROP COLUMN Zone,
-- MODIFY Street VARCHAR(63),
-- MODIFY City VARCHAR(63),
-- MODIFY Canton VARCHAR(16),
-- MODIFY Zip MEDIUMINT UNSIGNED,
-- MODIFY Rating TINYINT UNSIGNED,
-- MODIFY HasParking BOOLEAN,
-- MODIFY ParkingSpots TINYINT UNSIGNED,
-- MODIFY ParkingSurface SMALLINT UNSIGNED,
-- MODIFY TerrainDescription VARCHAR(255),
-- MODIFY TerrainSurface SMALLINT UNSIGNED,
-- MODIFY AdvisorId INT NOT NULL,
-- ADD CONSTRAINT FOREIGN KEY (AdvisorId) REFERENCES User (Id),
-- MODIFY Equipements TINYINT UNSIGNED,
-- MODIFY ParkingType TINYINT UNSIGNED,
-- MODIFY ReceivedDate DATE,
-- MODIFY ExpertizedDate DATE,
-- MODIFY NotarizedDate DATE,
-- MODIFY PaidDate DATE,
-- MODIFY DecidedDate DATE,
-- MODIFY TransmitedDate DATE,
-- MODIFY isPPE BOOLEAN

-- UPDATE BaseOwner SET Birthday = NULL WHERE Birthday = '';
-- UPDATE BaseOwner SET CivilStatus = NULL WHERE CivilStatus = '';
-- UPDATE BaseOwner SET Zip = NULL WHERE Zip = '';

-- ALTER TABLE BaseOwner
-- ADD PRIMARY KEY (Id),
-- MODIFY Id INT AUTO_INCREMENT,
-- MODIFY FirstName VARCHAR(63),
-- MODIFY LastName VARCHAR(63),
-- MODIFY Sex TINYINT(1),
-- MODIFY EMail VARCHAR(127),
-- MODIFY Phone VARCHAR(63),
-- MODIFY Birthday DATE,
-- MODIFY CivilStatus TINYINT UNSIGNED
-- MODIFY Street VARCHAR(63),
-- MODIFY City VARCHAR(63),
-- MODIFY Canton VARCHAR(16),
-- MODIFY Zip MEDIUMINT UNSIGNED,
-- MODIFY IsInFant BOOLEAN

-- CREATE TABLE Contact LIKE BaseOwner;
-- INSERT INTO Contact SELECT * FROM BaseOwner;

-- RENAME TABLE BaseOwner to Owner;
-- DELETE FROM Owner WHERE OwnerType = 'Contact';
-- DELETE FROM Contact WHERE OwnerType = 'Owner';

-- ALTER TABLE Owner 
-- DROP COLUMN OwnerType,
-- DROP COLUMN InfantAccountId,
-- DROP COLUMN IsInFant,
-- RENAME COLUMN OwnerAccountId TO AccountId;

-- ALTER TABLE Owner
-- MODIFY AccountId INT NOT NULL,
-- ADD CONSTRAINT FOREIGN KEY (AccountId) REFERENCES Account (Id);

-- ALTER TABLE Contact
-- DROP COLUMN OwnerType,
-- DROP COLUMN OwnerAccountId,
-- DROP COLUMN AVS,
-- DROP COLUMN Birthday,
-- DROP COLUMN CivilStatus,
-- DROP COLUMN Street,
-- DROP COLUMN City,
-- DROP COLUMN Canton,
-- DROP COLUMN Zip,
-- RENAME COLUMN InfantAccountId TO AccountId;

-- ALTER TABLE Contact
-- MODIFY AccountId INT NOT NULL,
-- ADD CONSTRAINT FOREIGN KEY (AccountId) REFERENCES Account (Id);

DESCRIBE Document

-- ALTER TABLE Document
-- ADD PRIMARY KEY (Id),
-- MODIFY Id int UNSIGNED AUTO_INCREMENT;