CREATE TABLE Contact LIKE BaseOwner;
INSERT INTO Contact SELECT * FROM BaseOwner;
RENAME TABLE BaseOwner to Owner;

DELETE FROM Owner WHERE OwnerType = 'Contact';
DELETE FROM Contact WHERE OwnerType = 'Owner';

ALTER TABLE Owner 
DROP COLUMN OwnerType,
DROP COLUMN InfantAccountId,
DROP COLUMN IsInFant,
RENAME COLUMN OwnerAccountId TO AccountId;

ALTER TABLE Contact
DROP COLUMN OwnerType,
DROP COLUMN OwnerAccountId,
DROP COLUMN AVS,
DROP COLUMN Birthday,
DROP COLUMN CivilStatus,
DROP COLUMN Street,
DROP COLUMN City,
DROP COLUMN Canton,
DROP COLUMN Zip,
RENAME COLUMN InfantAccountId TO AccountId;

ALTER TABLE Account
ADD PRIMARY KEY (Id),
MODIFY Id tinyint(4) AUTO_INCREMENT;
ALTER TABLE Company
ADD PRIMARY KEY (Id),
MODIFY Id tinyint(4) AUTO_INCREMENT;
ALTER TABLE Contact
ADD PRIMARY KEY (Id),
MODIFY Id tinyint(4) AUTO_INCREMENT;
ALTER TABLE Document
ADD PRIMARY KEY (Id),
MODIFY Id smallint(4) AUTO_INCREMENT;
ALTER TABLE Owner
ADD PRIMARY KEY (Id),
MODIFY Id tinyint(4) AUTO_INCREMENT;
ALTER TABLE Team
ADD PRIMARY KEY (Id),
MODIFY Id tinyint(4) AUTO_INCREMENT;
ALTER TABLE User
ADD PRIMARY KEY (Id),
MODIFY Id tinyint(4) AUTO_INCREMENT;