name: Macos

on: workflow_dispatch
  # push

env:
  BUILD_TYPE: Release
  MIN_OSX_VERSION: 11.0

jobs:
  build_release:
      strategy:
        matrix:
          include:
            - {os: macos-14, chip: arm}
            - {os: macos-13, chip: intel}

      runs-on: ${{matrix.os}}

      steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja qt
      - run: mkdir build

      - name: Configure CMake
        working-directory: ./build
        run: >
          cmake .. -GNinja
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_OSX_DEPLOYMENT_TARGET=${{env.MIN_OSX_VERSION}}

      - name: Build
        run: cmake --build build --target all

      - uses: actions/upload-artifact@v4
        with:
          name: viage_${{matrix.chip}}
          path: ${{github.workspace}}/build/bin/viage.dmg
